#!/bin/bash
#
# Description: This script cleans up everything generated by other scripts
#

. variables.sh


for mountpoint_ in dev sys proc opt; do
	while mountpoint -q ${ROOTFS_DIR}/${mountpoint_}; do
		sudo umount ${ROOTFS_DIR}/${mountpoint_}
	done
done

function do_cleanup() {
	echo -n "Cleaning up files ... "
	for trash_file in  ${ROOTFS_IMG} ${APP_IMG} ${OUT_KERNEL_IMG} ${OUT_ROOTFS_IMG} ${OUT_KERNEL_IMG}.md5sum ${OUT_ROOTFS_IMG}.md5sum app_app.ver rootfs_app.ver output/w2s_copy_dropbear.sh output/wcv3_flash-helper.conf; do
		[ -f ${trash_file} ] && rm -f ${trash_file}
	done

	[ -d output/dropbear ] && rm -rf output/dropbear
	rm -rf ${ROOTFS_DIR}
}

do_cleanup || { echo "failed, trying again" ; do_cleanup ; } && echo "done"
